version: '3.7'

services:
    deno:
        build: .
        env_file:
            - .env
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        ports:
            - 8080:8080
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: db
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d db"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        ports:
            - 5432:5432

volumes:
    db:
